### PR TITLE
termnate_existing_conns

### PR DESCRIPTION
**Pull request by avarlamov87**

### CODE REVIEW

**Comment by mohrezaei** [comment]
Thanks for the contribution. Can you please describe the motivation for this?

Also, per the [CONTRIBUTING.md](https://github.com/goldmansachs/jrpip/blob/master/CONTRIBUTING.md), since this is your first PR, please add a .dco file to the PR.

**Comment by avarlamov87** [comment]
> Thanks for the contribution. Can you please describe the motivation for this?

I need the ability to stop all remote invocations. But when i invoke stop and destroy SocketServer, only new connections will be refused. Already established connections still working and processes remote requests.
This new method add ability to close all connections and really stop processing requests.

> Also, per the [CONTRIBUTING.md](https://github.com/goldmansachs/jrpip/blob/master/CONTRIBUTING.md), since this is your first PR, please add a .dco file to the PR.
done.

**Comment by mohrezaei** [comment]
> I need the ability to stop all remote invocations. But when i invoke stop and destroy SocketServer, only new connections will be refused. Already established connections still working and processes remote requests.

Ok, thanks for the explanation. I understand your use case. Code looks good. Merging. When do you need a release?

**Comment by avarlamov87** [comment]
> Code looks good. Merging. 
Thanks

>When do you need a release?
ASAP

**Comment by mohrezaei** [comment]
[Released.](https://search.maven.org/artifact/com.goldmansachs.jrpip/jrpip/5.1.3/bundle)

Please note that maven repos can take up to a day to sync.

**Pull request merged**
